<?php
echo '<h1>Login</h1>';

echo '<span style="color:red" >'.$messages.'</span>';
$form = $this->form;
$form->prepare();
// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('user_management/default', array('controller' => 'user', 'action' => 'login'))); //'contact/process'));
// Set the method attribute for the form
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
echo $this->formRow($form->get('user_email'));
echo "<br> ";

echo $this->formRow($form->get('user_password'));
echo "<br> ";

echo $this->formRow($form->get('submit'));
//print_r($product);
//echo $this->form()->openTag($form);
//echo $this->formCollection($form);
echo $this->form()->closeTag();